name: Go

on:
  push:
    branches: 
      - stage 
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: remote to ssh
      uses: appleboy/ssh-action@v1.0.3
      with: 
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd $home
          mkdir coba-coba
