name: CI/CD

on:
  push:
    branches: 
      - stage 
jobs:
  build: 
    name: Build images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: mrido10
          registry: https://ghcr.io
          password: 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
      
      - name: Build and push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true

  deploy:
    name: Deploy to vps
    runs-on: ubuntu-latest
    steps:
    - name: remote to ssh
      uses: appleboy/ssh-action@v1.0.3
      with: 
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd docker_compose_files
          sudo docker pull ghcr.io/mrido10/coba-test
